{"version":1,"sembast":1}
{"key":1,"store":"tiker","value":{"id":1,"stock":"STOCK 0","name":"name 0","logo":"logo 0","sector":"sector 0","type":"type 0"}}
{"key":2,"store":"tiker","value":{"id":2,"stock":"STOCK 1","name":"name 1","logo":"logo 1","sector":"sector 1","type":"type 1"}}
{"key":3,"store":"tiker","value":{"id":3,"stock":"STOCK 2","name":"name 2","logo":"logo 2","sector":"sector 2","type":"type 2"}}
{"key":4,"store":"tiker","value":{"id":4,"stock":"STOCK 3","name":"name 3","logo":"logo 3","sector":"sector 3","type":"type 3"}}
{"key":5,"store":"tiker","value":{"id":5,"stock":"STOCK 4","name":"name 4","logo":"logo 4","sector":"sector 4","type":"type 4"}}
{"key":6,"store":"tiker","value":{"id":6,"stock":"STOCK 5","name":"name 5","logo":"logo 5","sector":"sector 5","type":"type 5"}}
{"key":7,"store":"tiker","value":{"id":7,"stock":"STOCK 6","name":"name 6","logo":"logo 6","sector":"sector 6","type":"type 6"}}
{"key":8,"store":"tiker","value":{"id":8,"stock":"STOCK 7","name":"name 7","logo":"logo 7","sector":"sector 7","type":"type 7"}}
{"key":9,"store":"tiker","value":{"id":9,"stock":"STOCK 8","name":"name 8","logo":"logo 8","sector":"sector 8","type":"type 8"}}
{"key":10,"store":"tiker","value":{"id":10,"stock":"STOCK 9","name":"name 9","logo":"logo 9","sector":"sector 9","type":"type 9"}}
{"key":11,"store":"tiker","value":{"id":11,"stock":"STOCK 10","name":"name 10","logo":"logo 10","sector":"sector 10","type":"type 10"}}
{"key":12,"store":"tiker","value":{"id":12,"stock":"STOCK 11","name":"name 11","logo":"logo 11","sector":"sector 11","type":"type 11"}}
{"key":13,"store":"tiker","value":{"id":13,"stock":"STOCK 12","name":"name 12","logo":"logo 12","sector":"sector 12","type":"type 12"}}
{"key":14,"store":"tiker","value":{"id":14,"stock":"STOCK 13","name":"name 13","logo":"logo 13","sector":"sector 13","type":"type 13"}}
{"key":15,"store":"tiker","value":{"id":15,"stock":"STOCK 14","name":"name 14","logo":"logo 14","sector":"sector 14","type":"type 14"}}
{"key":16,"store":"tiker","value":{"id":16,"stock":"STOCK 15","name":"name 15","logo":"logo 15","sector":"sector 15","type":"type 15"}}
{"key":17,"store":"tiker","value":{"id":17,"stock":"STOCK 16","name":"name 16","logo":"logo 16","sector":"sector 16","type":"type 16"}}
{"key":18,"store":"tiker","value":{"id":18,"stock":"STOCK 17","name":"name 17","logo":"logo 17","sector":"sector 17","type":"type 17"}}
{"key":19,"store":"tiker","value":{"id":19,"stock":"STOCK 18","name":"name 18","logo":"logo 18","sector":"sector 18","type":"type 18"}}
{"key":20,"store":"tiker","value":{"id":20,"stock":"STOCK 19","name":"name 19","logo":"logo 19","sector":"sector 19","type":"type 19"}}
{"key":21,"store":"tiker","value":{"id":21,"stock":"STOCK 20","name":"name 20","logo":"logo 20","sector":"sector 20","type":"type 20"}}
{"key":22,"store":"tiker","value":{"id":22,"stock":"STOCK 21","name":"name 21","logo":"logo 21","sector":"sector 21","type":"type 21"}}
{"key":23,"store":"tiker","value":{"id":23,"stock":"STOCK 22","name":"name 22","logo":"logo 22","sector":"sector 22","type":"type 22"}}
{"key":24,"store":"tiker","value":{"id":24,"stock":"STOCK 23","name":"name 23","logo":"logo 23","sector":"sector 23","type":"type 23"}}
{"key":25,"store":"tiker","value":{"id":25,"stock":"STOCK 24","name":"name 24","logo":"logo 24","sector":"sector 24","type":"type 24"}}
{"key":26,"store":"tiker","value":{"id":26,"stock":"STOCK 25","name":"name 25","logo":"logo 25","sector":"sector 25","type":"type 25"}}
{"key":27,"store":"tiker","value":{"id":27,"stock":"STOCK 26","name":"name 26","logo":"logo 26","sector":"sector 26","type":"type 26"}}
{"key":28,"store":"tiker","value":{"id":28,"stock":"STOCK 27","name":"name 27","logo":"logo 27","sector":"sector 27","type":"type 27"}}
{"key":29,"store":"tiker","value":{"id":29,"stock":"STOCK 28","name":"name 28","logo":"logo 28","sector":"sector 28","type":"type 28"}}
{"key":30,"store":"tiker","value":{"id":30,"stock":"STOCK 29","name":"name 29","logo":"logo 29","sector":"sector 29","type":"type 29"}}
{"key":31,"store":"tiker","value":{"id":31,"stock":"STOCK 30","name":"name 30","logo":"logo 30","sector":"sector 30","type":"type 30"}}
{"key":32,"store":"tiker","value":{"id":32,"stock":"STOCK 31","name":"name 31","logo":"logo 31","sector":"sector 31","type":"type 31"}}
{"key":33,"store":"tiker","value":{"id":33,"stock":"STOCK 32","name":"name 32","logo":"logo 32","sector":"sector 32","type":"type 32"}}
{"key":34,"store":"tiker","value":{"id":34,"stock":"STOCK 33","name":"name 33","logo":"logo 33","sector":"sector 33","type":"type 33"}}
{"key":35,"store":"tiker","value":{"id":35,"stock":"STOCK 34","name":"name 34","logo":"logo 34","sector":"sector 34","type":"type 34"}}
{"key":36,"store":"tiker","value":{"id":36,"stock":"STOCK 35","name":"name 35","logo":"logo 35","sector":"sector 35","type":"type 35"}}
{"key":37,"store":"tiker","value":{"id":37,"stock":"STOCK 36","name":"name 36","logo":"logo 36","sector":"sector 36","type":"type 36"}}
{"key":38,"store":"tiker","value":{"id":38,"stock":"STOCK 37","name":"name 37","logo":"logo 37","sector":"sector 37","type":"type 37"}}
{"key":39,"store":"tiker","value":{"id":39,"stock":"STOCK 38","name":"name 38","logo":"logo 38","sector":"sector 38","type":"type 38"}}
{"key":40,"store":"tiker","value":{"id":40,"stock":"STOCK 39","name":"name 39","logo":"logo 39","sector":"sector 39","type":"type 39"}}
{"key":41,"store":"tiker","value":{"id":41,"stock":"STOCK 40","name":"name 40","logo":"logo 40","sector":"sector 40","type":"type 40"}}
{"key":42,"store":"tiker","value":{"id":42,"stock":"STOCK 41","name":"name 41","logo":"logo 41","sector":"sector 41","type":"type 41"}}
{"key":43,"store":"tiker","value":{"id":43,"stock":"STOCK 42","name":"name 42","logo":"logo 42","sector":"sector 42","type":"type 42"}}
{"key":44,"store":"tiker","value":{"id":44,"stock":"STOCK 43","name":"name 43","logo":"logo 43","sector":"sector 43","type":"type 43"}}
{"key":45,"store":"tiker","value":{"id":45,"stock":"STOCK 44","name":"name 44","logo":"logo 44","sector":"sector 44","type":"type 44"}}
{"key":46,"store":"tiker","value":{"id":46,"stock":"STOCK 45","name":"name 45","logo":"logo 45","sector":"sector 45","type":"type 45"}}
{"key":47,"store":"tiker","value":{"id":47,"stock":"STOCK 46","name":"name 46","logo":"logo 46","sector":"sector 46","type":"type 46"}}
{"key":48,"store":"tiker","value":{"id":48,"stock":"STOCK 47","name":"name 47","logo":"logo 47","sector":"sector 47","type":"type 47"}}
{"key":49,"store":"tiker","value":{"id":49,"stock":"STOCK 48","name":"name 48","logo":"logo 48","sector":"sector 48","type":"type 48"}}
{"key":50,"store":"tiker","value":{"id":50,"stock":"STOCK 49","name":"name 49","logo":"logo 49","sector":"sector 49","type":"type 49"}}
{"key":51,"store":"tiker","value":{"id":51,"stock":"STOCK 50","name":"name 50","logo":"logo 50","sector":"sector 50","type":"type 50"}}
{"key":52,"store":"tiker","value":{"id":52,"stock":"STOCK 51","name":"name 51","logo":"logo 51","sector":"sector 51","type":"type 51"}}
{"key":53,"store":"tiker","value":{"id":53,"stock":"STOCK 52","name":"name 52","logo":"logo 52","sector":"sector 52","type":"type 52"}}
{"key":54,"store":"tiker","value":{"id":54,"stock":"STOCK 53","name":"name 53","logo":"logo 53","sector":"sector 53","type":"type 53"}}
{"key":55,"store":"tiker","value":{"id":55,"stock":"STOCK 54","name":"name 54","logo":"logo 54","sector":"sector 54","type":"type 54"}}
{"key":56,"store":"tiker","value":{"id":56,"stock":"STOCK 55","name":"name 55","logo":"logo 55","sector":"sector 55","type":"type 55"}}
{"key":57,"store":"tiker","value":{"id":57,"stock":"STOCK 56","name":"name 56","logo":"logo 56","sector":"sector 56","type":"type 56"}}
{"key":58,"store":"tiker","value":{"id":58,"stock":"STOCK 57","name":"name 57","logo":"logo 57","sector":"sector 57","type":"type 57"}}
{"key":59,"store":"tiker","value":{"id":59,"stock":"STOCK 58","name":"name 58","logo":"logo 58","sector":"sector 58","type":"type 58"}}
{"key":60,"store":"tiker","value":{"id":60,"stock":"STOCK 59","name":"name 59","logo":"logo 59","sector":"sector 59","type":"type 59"}}
{"key":61,"store":"tiker","value":{"id":61,"stock":"STOCK 60","name":"name 60","logo":"logo 60","sector":"sector 60","type":"type 60"}}
{"key":62,"store":"tiker","value":{"id":62,"stock":"STOCK 61","name":"name 61","logo":"logo 61","sector":"sector 61","type":"type 61"}}
{"key":63,"store":"tiker","value":{"id":63,"stock":"STOCK 62","name":"name 62","logo":"logo 62","sector":"sector 62","type":"type 62"}}
{"key":64,"store":"tiker","value":{"id":64,"stock":"STOCK 63","name":"name 63","logo":"logo 63","sector":"sector 63","type":"type 63"}}
{"key":65,"store":"tiker","value":{"id":65,"stock":"STOCK 64","name":"name 64","logo":"logo 64","sector":"sector 64","type":"type 64"}}
{"key":66,"store":"tiker","value":{"id":66,"stock":"STOCK 65","name":"name 65","logo":"logo 65","sector":"sector 65","type":"type 65"}}
{"key":67,"store":"tiker","value":{"id":67,"stock":"STOCK 66","name":"name 66","logo":"logo 66","sector":"sector 66","type":"type 66"}}
{"key":68,"store":"tiker","value":{"id":68,"stock":"STOCK 67","name":"name 67","logo":"logo 67","sector":"sector 67","type":"type 67"}}
{"key":69,"store":"tiker","value":{"id":69,"stock":"STOCK 68","name":"name 68","logo":"logo 68","sector":"sector 68","type":"type 68"}}
{"key":70,"store":"tiker","value":{"id":70,"stock":"STOCK 69","name":"name 69","logo":"logo 69","sector":"sector 69","type":"type 69"}}
{"key":71,"store":"tiker","value":{"id":71,"stock":"STOCK 70","name":"name 70","logo":"logo 70","sector":"sector 70","type":"type 70"}}
{"key":72,"store":"tiker","value":{"id":72,"stock":"STOCK 71","name":"name 71","logo":"logo 71","sector":"sector 71","type":"type 71"}}
{"key":73,"store":"tiker","value":{"id":73,"stock":"STOCK 72","name":"name 72","logo":"logo 72","sector":"sector 72","type":"type 72"}}
{"key":74,"store":"tiker","value":{"id":74,"stock":"STOCK 73","name":"name 73","logo":"logo 73","sector":"sector 73","type":"type 73"}}
{"key":75,"store":"tiker","value":{"id":75,"stock":"STOCK 74","name":"name 74","logo":"logo 74","sector":"sector 74","type":"type 74"}}
{"key":76,"store":"tiker","value":{"id":76,"stock":"STOCK 75","name":"name 75","logo":"logo 75","sector":"sector 75","type":"type 75"}}
{"key":77,"store":"tiker","value":{"id":77,"stock":"STOCK 76","name":"name 76","logo":"logo 76","sector":"sector 76","type":"type 76"}}
{"key":78,"store":"tiker","value":{"id":78,"stock":"STOCK 77","name":"name 77","logo":"logo 77","sector":"sector 77","type":"type 77"}}
{"key":79,"store":"tiker","value":{"id":79,"stock":"STOCK 78","name":"name 78","logo":"logo 78","sector":"sector 78","type":"type 78"}}
{"key":80,"store":"tiker","value":{"id":80,"stock":"STOCK 79","name":"name 79","logo":"logo 79","sector":"sector 79","type":"type 79"}}
{"key":81,"store":"tiker","value":{"id":81,"stock":"STOCK 80","name":"name 80","logo":"logo 80","sector":"sector 80","type":"type 80"}}
{"key":82,"store":"tiker","value":{"id":82,"stock":"STOCK 81","name":"name 81","logo":"logo 81","sector":"sector 81","type":"type 81"}}
{"key":83,"store":"tiker","value":{"id":83,"stock":"STOCK 82","name":"name 82","logo":"logo 82","sector":"sector 82","type":"type 82"}}
{"key":84,"store":"tiker","value":{"id":84,"stock":"STOCK 83","name":"name 83","logo":"logo 83","sector":"sector 83","type":"type 83"}}
{"key":85,"store":"tiker","value":{"id":85,"stock":"STOCK 84","name":"name 84","logo":"logo 84","sector":"sector 84","type":"type 84"}}
{"key":86,"store":"tiker","value":{"id":86,"stock":"STOCK 85","name":"name 85","logo":"logo 85","sector":"sector 85","type":"type 85"}}
{"key":87,"store":"tiker","value":{"id":87,"stock":"STOCK 86","name":"name 86","logo":"logo 86","sector":"sector 86","type":"type 86"}}
{"key":88,"store":"tiker","value":{"id":88,"stock":"STOCK 87","name":"name 87","logo":"logo 87","sector":"sector 87","type":"type 87"}}
{"key":89,"store":"tiker","value":{"id":89,"stock":"STOCK 88","name":"name 88","logo":"logo 88","sector":"sector 88","type":"type 88"}}
{"key":90,"store":"tiker","value":{"id":90,"stock":"STOCK 89","name":"name 89","logo":"logo 89","sector":"sector 89","type":"type 89"}}
{"key":91,"store":"tiker","value":{"id":91,"stock":"STOCK 90","name":"name 90","logo":"logo 90","sector":"sector 90","type":"type 90"}}
{"key":92,"store":"tiker","value":{"id":92,"stock":"STOCK 91","name":"name 91","logo":"logo 91","sector":"sector 91","type":"type 91"}}
{"key":93,"store":"tiker","value":{"id":93,"stock":"STOCK 92","name":"name 92","logo":"logo 92","sector":"sector 92","type":"type 92"}}
{"key":94,"store":"tiker","value":{"id":94,"stock":"STOCK 93","name":"name 93","logo":"logo 93","sector":"sector 93","type":"type 93"}}
{"key":95,"store":"tiker","value":{"id":95,"stock":"STOCK 94","name":"name 94","logo":"logo 94","sector":"sector 94","type":"type 94"}}
{"key":96,"store":"tiker","value":{"id":96,"stock":"STOCK 95","name":"name 95","logo":"logo 95","sector":"sector 95","type":"type 95"}}
{"key":97,"store":"tiker","value":{"id":97,"stock":"STOCK 96","name":"name 96","logo":"logo 96","sector":"sector 96","type":"type 96"}}
{"key":98,"store":"tiker","value":{"id":98,"stock":"STOCK 97","name":"name 97","logo":"logo 97","sector":"sector 97","type":"type 97"}}
{"key":99,"store":"tiker","value":{"id":99,"stock":"STOCK 98","name":"name 98","logo":"logo 98","sector":"sector 98","type":"type 98"}}
{"key":100,"store":"tiker","value":{"id":100,"stock":"STOCK 99","name":"name 99","logo":"logo 99","sector":"sector 99","type":"type 99"}}
